export type Tea = {
  id: string;
  name: string;
  seconds: number;
  tempC: number;
  emoji: string;
  hint: string;
  popularity: number;
};

// Tiempos recomendados de infusión y temperaturas.
// Fuentes: guías generales de tetería (valores promedio por hoja suelta).
export const TEAS: Tea[] = [
  {
    id: "negro",
    name: "Té Negro",
    seconds: 180,
    tempC: 95,
    emoji: "🫖",
    hint: "Robusto y clásico",
    popularity: 100,
  },
  {
    id: "verde",
    name: "Té Verde",
    seconds: 150,
    tempC: 80,
    emoji: "🍵",
    hint: "Fresco y herbal",
    popularity: 95,
  },
  {
    id: "manzanilla",
    name: "Manzanilla",
    seconds: 300,
    tempC: 95,
    emoji: "🌼",
    hint: "Suave y relajante",
    popularity: 92,
  },
  {
    id: "mate-cocido",
    name: "Mate Cocido",
    seconds: 240,
    tempC: 80,
    emoji: "🧉",
    hint: "Típico del Río de la Plata",
    popularity: 90,
  },
  {
    id: "earl-grey",
    name: "Earl Grey",
    seconds: 240,
    tempC: 95,
    emoji: "🌸",
    hint: "Negro con bergamota",
    popularity: 85,
  },
  {
    id: "rooibos",
    name: "Rooibos",
    seconds: 360,
    tempC: 100,
    emoji: "🌿",
    hint: "Sin cafeína, dulce",
    popularity: 78,
  },
  {
    id: "blanco",
    name: "Té Blanco",
    seconds: 240,
    tempC: 80,
    emoji: "🤍",
    hint: "Delicado y floral",
    popularity: 72,
  },
  {
    id: "oolong",
    name: "Oolong",
    seconds: 180,
    tempC: 90,
    emoji: "🍃",
    hint: "Entre verde y negro",
    popularity: 70,
  },
  {
    id: "chai",
    name: "Chai",
    seconds: 300,
    tempC: 100,
    emoji: "🌶️",
    hint: "Negro especiado",
    popularity: 68,
  },
  {
    id: "jazmin",
    name: "Té de Jazmín",
    seconds: 180,
    tempC: 80,
    emoji: "💮",
    hint: "Verde perfumado",
    popularity: 65,
  },
  {
    id: "menta",
    name: "Menta",
    seconds: 300,
    tempC: 100,
    emoji: "🌱",
    hint: "Digestivo",
    popularity: 62,
  },
  {
    id: "pu-erh",
    name: "Pu-erh",
    seconds: 240,
    tempC: 95,
    emoji: "🪵",
    hint: "Fermentado, terroso",
    popularity: 55,
  },
  {
    id: "matcha",
    name: "Matcha",
    seconds: 30,
    tempC: 75,
    emoji: "🍵",
    hint: "Batir con chasen",
    popularity: 60,
  },
  {
    id: "english-breakfast",
    name: "English Breakfast",
    seconds: 240,
    tempC: 95,
    emoji: "☕",
    hint: "Desayuno inglés",
    popularity: 58,
  },
  {
    id: "hibisco",
    name: "Hibisco",
    seconds: 300,
    tempC: 100,
    emoji: "🌺",
    hint: "Ácido, rubí",
    popularity: 50,
  },
  {
    id: "tilo",
    name: "Tilo",
    seconds: 300,
    tempC: 95,
    emoji: "🌳",
    hint: "Calmante",
    popularity: 48,
  },
  {
    id: "jengibre",
    name: "Jengibre",
    seconds: 420,
    tempC: 100,
    emoji: "🫚",
    hint: "Picante, inmunidad",
    popularity: 45,
  },
  {
    id: "boldo",
    name: "Boldo",
    seconds: 300,
    tempC: 100,
    emoji: "🍂",
    hint: "Digestivo intenso",
    popularity: 40,
  },
];

export const getTeaById = (id: string) => TEAS.find((t) => t.id === id);
